---
.cache_bundler: &cache_bundler
  cache:
    untracked: true
    # A broad attempt at caching between runs (ala Travis CI)
    key: "${CI_PROJECT_NAMESPACE}__bundler"
    paths:
      - '.vendor'
      - 'vendor'

.setup_bundler_env: &setup_bundler_env
  before_script:
    - 'echo Files in cache: $(find .vendor | wc -l) || :'
    - 'export GEM_HOME=.vendor/gem_install'
    - 'export BUNDLE_CACHE_PATH=.vendor/bundler'
    - 'declare GEM_BUNDLER_VER=(-v ''~> ${BUNDLER_VERSION:-1.16.0}'')'
    - declare GEM_INSTALL=(gem install --no-document)
    - declare BUNDLER_INSTALL=(bundle install --no-binstubs --jobs $(nproc) --path=.vendor "${FLAGS[@]}")
    - gem list -ie "${GEM_BUNDLE_VER[@]}" --silent bundler || "${GEM_INSTALL[@]}" --local "${GEM_BUNDLE_VER[@]}" bundler || "${GEM_INSTALL[@]}" "${GEM_BUNDLE_VER[@]}" bundler
    - 'rm -rf pkg/ || :'
    - bundle check || rm -f Gemfile.lock && ("${BUNDLER_INSTALL[@]}" --local || "${BUNDLER_INSTALL[@]}")


.validation_checks: &validation_checks
  script:
    - bundle exec rake syntax
    - bundle exec rake check:dot_underscore
    - bundle exec rake check:test_file
    - bundle exec rake lint
    # - bundle exec rake pkg:check_version
    # - bundle exec rake pkg:compare_latest_tag

.spec_tests: &spec_tests
  script:
    - bundle exec rake spec

# To avoid running a prohibitive number of tests every commit,
# don't set this env var in your gitlab instance
.only_with_SIMP_FULL_MATRIX: &only_with_SIMP_FULL_MATRIX
  only:
    variables:
      - $SIMP_FULL_MATRIX

stages:
  - validation
  - unit
  - acceptance
  - deploy

# Puppet 4.10 for PE 2017.2 support (EOL:2018-02-21)
# See: https://puppet.com/misc/puppet-enterprise-lifecycle
# --------------------------------------
2_1-validation:
  stage: validation
  tags:
    - docker
  image: ruby:2.1
  <<: *cache_bundler
  <<: *setup_bundler_env
  <<: *validation_checks

2_1-unit:
  stage: unit
  tags:
    - docker
  image: ruby:2.1
  <<: *cache_bundler
  <<: *setup_bundler_env
  <<: *spec_tests

# Puppet 4.10 for PE 2017.2 support (EOL:2018-02-21)
# See: https://puppet.com/misc/puppet-enterprise-lifecycle
# --------------------------------------
2_4-validation:
  stage: validation
  tags:
    - docker
  image: ruby:2.4
  <<: *cache_bundler
  <<: *setup_bundler_env
  <<: *validation_checks

2_4-unit:
  stage: unit
  tags:
    - docker
  image: ruby:2.4
  <<: *cache_bundler
  <<: *setup_bundler_env
  <<: *spec_tests


#=======================================================================
# Acceptance tests
default:
  stage: acceptance
  tags:
    - beaker
  <<: *cache_bundler
  <<: *setup_bundler_env
  variables:
    PUPPET_VERSION: '~> 4.10.10'
  script:
    - bundle exec rake spec_clean
    - bundle exec rake beaker:suites[default]

default-puppet5:
  stage: acceptance
  tags:
    - beaker
  <<: *cache_bundler
  <<: *setup_bundler_env
  variables:
    PUPPET_VERSION: '~> 5.3'
    BEAKER_PUPPET_COLLECTION: 'puppet5'
  script:
    - bundle exec rake spec_clean
    - bundle exec rake beaker:suites[default]

default-fips:
  stage: acceptance
  tags:
    - beaker
  <<: *cache_bundler
  <<: *setup_bundler_env
  variables:
    BEAKER_fips: 'yes'
  script:
    - bundle exec rake spec_clean
    - bundle exec rake beaker:suites[default]

fips_from_fixtures:
  stage: acceptance
  tags:
    - beaker
  <<: *cache_bundler
  <<: *setup_bundler_env
  variables:
    PUPPET_VERSION: '~> 5.3'
    BEAKER_PUPPET_COLLECTION: 'puppet5'
  script:
    - bundle exec rake spec_clean
    - bundle exec rake beaker:suites[fips_from_fixtures]

puppet_collections:
  stage: acceptance
  tags:
    - beaker
  <<: *cache_bundler
  <<: *setup_bundler_env
  variables:
    PUPPET_VERSION: '~> 5.3'
    BEAKER_PUPPET_COLLECTION: 'puppet5'
  script:
    - bundle exec rake spec_clean
    - bundle exec rake beaker:suites[puppet_collections]

windows:
  stage: acceptance
  tags:
    - beaker
  <<: *cache_bundler
  <<: *setup_bundler_env
  script:
    - bundle exec rake spec_clean
    - bundle exec rake beaker:suites[windows]
